### ISSUE TITLE
Seems broken

### ISSUE THREAD

**Issue by zjiekai** [theelous3/asks#105]
```
Package          Version
---------------- -------
asks             2.2.0  
async-generator  1.10   
attrs            18.2.0 
contextvars      2.3    
h11              0.8.1  
idna             2.8    
immutables       0.6    
multio           0.2.4  
outcome          1.0.0  
pip              19.0.2 
pipdeptree       0.13.2 
pkg-resources    0.0.0  
setuptools       20.7.0 
sniffio          1.0.0  
sortedcontainers 2.1.0  
trio             0.11.0 

```

```python
import asks
import trio

asks.init('trio')

```
```
Traceback (most recent call last):
  File "ask.py", line 4, in <module>
    asks.init('trio')
  File "/mnt/py3venv/trio/lib/python3.5/site-packages/multio/__init__.py", line 510, in init
    manager.init(library, asynclib)
  File "/mnt/py3venv/trio/lib/python3.5/site-packages/multio/__init__.py", line 260, in init
    return self._handlers[library](lib)
  File "/mnt/py3venv/trio/lib/python3.5/site-packages/multio/__init__.py", line 466, in _trio_init
    lib.Queue = trio.Queue
  File "/mnt/py3venv/trio/lib/python3.5/site-packages/trio/_deprecate.py", line 125, in __getattr__
    raise AttributeError(name)
AttributeError: Queue
```

**Comment by theelous3** [comment]
This is from multio, which is currently driving the trio/curio interactions with asks. It is fixed in https://github.com/theelous3/multio/pull/24
