### ISSUE TITLE
Dormant (server-closed) connections cause errors

### ISSUE THREAD

**Issue by smurfix** [theelous3/asks#115]
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/asks/sessions.py", line 184, in request
    sock, r = await req_obj.make_request()
  File "/usr/lib/python3/dist-packages/asks/request_object.py", line 217, in make_request
    response_obj = await self._request_io(req, req_body, hconnection)
  File "/usr/lib/python3/dist-packages/asks/request_object.py", line 254, in _request_io
    response_obj = await self._catch_response(hconnection)
  File "/usr/lib/python3/dist-packages/asks/request_object.py", line 535, in _catch_response
    response = await self._recv_event(hconnection)
  File "/usr/lib/python3/dist-packages/asks/request_object.py", line 611, in _recv_event
    event = hconnection.next_event()
  File "/usr/lib/python3/dist-packages/h11/_connection.py", line 439, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/usr/lib/python3/dist-packages/h11/_util.py", line 72, in _reraise_as_remote_protocol_error
    raise self
  File "/usr/lib/python3/dist-packages/h11/_connection.py", line 422, in next_event
    self._process_event(self.their_role, event)
  File "/usr/lib/python3/dist-packages/h11/_connection.py", line 238, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "/usr/lib/python3/dist-packages/h11/_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "/usr/lib/python3/dist-packages/h11/_state.py", line 253, in _fire_event_triggered_transitions
    .format(event_type.__name__, role, self.states[role]))
h11._util.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/trio_swagger11/http_client.py", line 200, in request
    method=method, url=url, params=params, data=data, headers=headers)
  File "/usr/lib/python3/dist-packages/asks/sessions.py", line 214, in request
    await self._handle_exception(e, sock)
  File "/usr/lib/python3/dist-packages/asks/sessions.py", line 252, in _handle_exception
    raise BadHttpResponse('Invalid HTTP response from server.') from e
asks.errors.BadHttpResponse: Invalid HTTP response from server.


```

**Comment by Giftcarder** [comment]
Same issue here

**Comment by theelous3** [comment]
This is something I encountered here: https://github.com/theelous3/asks/issues/107

I made a quick issue to take some notes at the time. I'm working on a test setup to replicate. I'll close the other issue and use this one.

**Comment by jgerry2002** [comment]
Any updates on this issue? I was testing and experience this same bug.

**Comment by theelous3** [comment]
@jgerry2002 can you elaborate on the conditions under which you encountered this?

**Comment by rnovatorov** [comment]
Getting the same error while talking to HTTP/1.0 servers.

According to [RFC-7230](https://tools.ietf.org/html/rfc7230#section-6.3) the connection will close 


```python
# server.py

from http.server import HTTPServer, BaseHTTPRequestHandler, HTTPStatus

class Handler(BaseHTTPRequestHandler):

    def do_GET(self):
        self.send_response(HTTPStatus.OK)
        # self.send_header("Connection", "close")
        self.send_header("Content-Length", "0")
        self.end_headers()

if __name__ == "__main__":
    HTTPServer(("", 8000), Handler).serve_forever()
```

```python
# client.py

import trio
import asks

async def main():
    session = asks.Session()
    for _ in range(2):
        await session.get("http://localhost:8000")

if __name__ == "__main__":
    trio.run(main)
```

**Comment by rnovatorov** [comment]
Getting the same error with `asks==2.3.5` while talking to HTTP/1.0 server using `asks.Session`.

**Steps to reproduce:**

```python
# server.py

from http.server import HTTPServer, BaseHTTPRequestHandler, HTTPStatus

class Handler(BaseHTTPRequestHandler):

    def do_GET(self):
        self.send_response(HTTPStatus.OK)
        # Uncomment to make client work
        # self.send_header("Connection", "close")
        self.send_header("Content-Length", "0")
        self.end_headers()

if __name__ == "__main__":
    HTTPServer(("", 8000), Handler).serve_forever()
```

```python
# client.py

import trio
import asks

async def main():
    session = asks.Session("http://localhost:8000")
    await session.get()  # OK
    await session.get()  # Fail

if __name__ == "__main__":
    trio.run(main)
```

**Expected result:**

According to [RFC-7230](https://tools.ietf.org/html/rfc7230#section-6.3) the connection will close if the received protocol is HTTP/1.0 and the "keep-alive" connection option is not present.

**Actual result:**

It seems like `asks` is trying to reuse the closed connection and fails with `BadHttpResponse`.

**Comment by theelous3** [comment]
Nice ty

**Comment by freis** [comment]
Was this issue addressed? I keep getting "Invalid HTTP response from server" when trying many connections using Trio.

**Comment by smurfix** [comment]
This issue exhibits two problems.

(a) asks doesn't notice that the connection will be closed (`HTTP/1.0` and no `connection:` header), 

(b) this should not be fatal as the server might close the connection anyway due to timeout or resource overload or whatever and the client must retry transparently if that happens.

**Comment by dismantl** [comment]
I'm hitting this error as well. I'm using asks/trio and have a session pool of 10 sessions continuously making requests to a remote server. The underlying exceptions come from h11 and seem to happen in batches (see stack trace below). I've tried recovering from these errors by returning the sessions to the session pool and continue using them (which works), but I noticed that it left a bunch of open TCP sockets whenever it hit these errors. Eventually all the orphaned TCP connections hit the process's limit on open file descriptors and it crashed.

```
Traceback (most recent call last):
  File "./src/case_harvester.py", line 293, in <module>
    args.func(args)
  File "./src/case_harvester.py", line 139, in run_spider
    spider.resume()
  File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 182, in resume
    self.start()
  File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 160, in start
    node.start(self.session_pool)
  File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 358, in start
    trio.run(self.__start_root, session_pool, restrict_keyboard_interrupt_to_checkpoints=True)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 1225, in run
    return result.unwrap()
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_result.py", line 119, in unwrap
    raise self.error
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 1334, in run_impl
    msg = task.coro.send(next_send)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 923, in init
    self.entry_queue.spawn()
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_util.py", line 109, in __aexit__
    await self._agen.asend(None)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/async_generator/_impl.py", line 366, in step
    return await ANextIter(self._it, start_fn, *args)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/async_generator/_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 318, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
    yield scope
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_multierror.py", line 144, in __exit__
    raise filtered_exc
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 1334, in run_impl
    msg = task.coro.send(next_send)
  File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 420, in __start_root
    nursery.start_soon(self.__state_manager, nursery)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_util.py", line 109, in __aexit__
    await self._agen.asend(None)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/async_generator/_impl.py", line 366, in step
    return await ANextIter(self._it, start_fn, *args)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/async_generator/_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 318, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
    yield scope
  File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_multierror.py", line 144, in __exit__
    raise filtered_exc
trio.MultiError: RemoteProtocolError("Can't receive data when peer state is ERROR"), RemoteProtocolError("Can't receive data when peer state is ERROR"), RemoteProtocolError("Can't receive data when peer state is ERROR"), RemoteProtocolError("Can't receive data when peer state is ERROR")

Details of embedded exception 1:

  Traceback (most recent call last):
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
      new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
  KeyError: <class 'h11._events.ConnectionClosed'>

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 520, in _catch_response
      response = await self._recv_event(hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 588, in _recv_event
      event = hconnection.next_event()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 444, in next_event
      exc._reraise_as_remote_protocol_error()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_util.py", line 80, in _reraise_as_remote_protocol_error
      raise self
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 427, in next_event
      self._process_event(self.their_role, event)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 242, in _process_event
      self._cstate.process_event(role, type(event), server_switch_event)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_state.py", line 238, in process_event
      self._fire_event_triggered_transitions(role, event_type)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_state.py", line 253, in _fire_event_triggered_transitions
      event_type.__name__, role, self.states[role]
  h11._util.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
      yield scope
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 318, in open_nursery
      await nursery._nested_child_finished(nested_child_exc)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 427, in _nested_child_finished
      raise MultiError(self._pending_excs)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 1334, in run_impl
      msg = task.coro.send(next_send)
    File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 441, in __start_child
      await self.__search(session_pool)
    File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 514, in __search
      xml = False
    File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 651, in __query_mjcs
      max_redirects = 1
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/sessions.py", line 163, in request
      sock, r = await self.timeout_manager(timeout, req_obj)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/sessions.py", line 188, in timeout_manager
      sock, r = await req_obj.make_request()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 205, in make_request
      response_obj = await self._request_io(req, req_body, hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 242, in _request_io
      response_obj = await self._catch_response(hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 523, in _catch_response
      response = await self._recv_event(hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 588, in _recv_event
      event = hconnection.next_event()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 423, in next_event
      raise RemoteProtocolError("Can't receive data when peer state is ERROR")
  h11._util.RemoteProtocolError: Can't receive data when peer state is ERROR

Details of embedded exception 2:

  Traceback (most recent call last):
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
      new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
  KeyError: <class 'h11._events.ConnectionClosed'>

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 520, in _catch_response
      response = await self._recv_event(hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 588, in _recv_event
      event = hconnection.next_event()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 444, in next_event
      exc._reraise_as_remote_protocol_error()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_util.py", line 80, in _reraise_as_remote_protocol_error
      raise self
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 427, in next_event
      self._process_event(self.their_role, event)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 242, in _process_event
      self._cstate.process_event(role, type(event), server_switch_event)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_state.py", line 238, in process_event
      self._fire_event_triggered_transitions(role, event_type)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_state.py", line 253, in _fire_event_triggered_transitions
      event_type.__name__, role, self.states[role]
  h11._util.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
      yield scope
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 318, in open_nursery
      await nursery._nested_child_finished(nested_child_exc)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 427, in _nested_child_finished
      raise MultiError(self._pending_excs)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 1334, in run_impl
      msg = task.coro.send(next_send)
    File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 441, in __start_child
      await self.__search(session_pool)
    File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 514, in __search
      xml = False
    File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 651, in __query_mjcs
      max_redirects = 1
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/sessions.py", line 163, in request
      sock, r = await self.timeout_manager(timeout, req_obj)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/sessions.py", line 188, in timeout_manager
      sock, r = await req_obj.make_request()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 205, in make_request
      response_obj = await self._request_io(req, req_body, hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 242, in _request_io
      response_obj = await self._catch_response(hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 523, in _catch_response
      response = await self._recv_event(hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 588, in _recv_event
      event = hconnection.next_event()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 423, in next_event
      raise RemoteProtocolError("Can't receive data when peer state is ERROR")
  h11._util.RemoteProtocolError: Can't receive data when peer state is ERROR

Details of embedded exception 3:

  Traceback (most recent call last):
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
      new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
  KeyError: <class 'h11._events.ConnectionClosed'>

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 520, in _catch_response
      response = await self._recv_event(hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 588, in _recv_event
      event = hconnection.next_event()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 444, in next_event
      exc._reraise_as_remote_protocol_error()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_util.py", line 80, in _reraise_as_remote_protocol_error
      raise self
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 427, in next_event
      self._process_event(self.their_role, event)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 242, in _process_event
      self._cstate.process_event(role, type(event), server_switch_event)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_state.py", line 238, in process_event
      self._fire_event_triggered_transitions(role, event_type)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_state.py", line 253, in _fire_event_triggered_transitions
      event_type.__name__, role, self.states[role]
  h11._util.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
      yield scope
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 318, in open_nursery
      await nursery._nested_child_finished(nested_child_exc)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 427, in _nested_child_finished
      raise MultiError(self._pending_excs)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 1334, in run_impl
      msg = task.coro.send(next_send)
    File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 441, in __start_child
      await self.__search(session_pool)
    File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 514, in __search
      xml = False
    File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 651, in __query_mjcs
      max_redirects = 1
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/sessions.py", line 163, in request
      sock, r = await self.timeout_manager(timeout, req_obj)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/sessions.py", line 188, in timeout_manager
      sock, r = await req_obj.make_request()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 205, in make_request
      response_obj = await self._request_io(req, req_body, hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 242, in _request_io
      response_obj = await self._catch_response(hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 523, in _catch_response
      response = await self._recv_event(hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 588, in _recv_event
      event = hconnection.next_event()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 423, in next_event
      raise RemoteProtocolError("Can't receive data when peer state is ERROR")
  h11._util.RemoteProtocolError: Can't receive data when peer state is ERROR

Details of embedded exception 4:

  Traceback (most recent call last):
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
      new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
  KeyError: <class 'h11._events.ConnectionClosed'>

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 520, in _catch_response
      response = await self._recv_event(hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 588, in _recv_event
      event = hconnection.next_event()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 444, in next_event
      exc._reraise_as_remote_protocol_error()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_util.py", line 80, in _reraise_as_remote_protocol_error
      raise self
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 427, in next_event
      self._process_event(self.their_role, event)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 242, in _process_event
      self._cstate.process_event(role, type(event), server_switch_event)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_state.py", line 238, in process_event
      self._fire_event_triggered_transitions(role, event_type)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_state.py", line 253, in _fire_event_triggered_transitions
      event_type.__name__, role, self.states[role]
  h11._util.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
      yield scope
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 318, in open_nursery
      await nursery._nested_child_finished(nested_child_exc)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 427, in _nested_child_finished
      raise MultiError(self._pending_excs)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 1334, in run_impl
      msg = task.coro.send(next_send)
    File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 441, in __start_child
      await self.__search(session_pool)
    File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 514, in __search
      xml = False
    File "/home/ubuntu/mjcs/src/mjcs/spider.py", line 651, in __query_mjcs
      max_redirects = 1
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/sessions.py", line 163, in request
      sock, r = await self.timeout_manager(timeout, req_obj)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/sessions.py", line 188, in timeout_manager
      sock, r = await req_obj.make_request()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 205, in make_request
      response_obj = await self._request_io(req, req_body, hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 242, in _request_io
      response_obj = await self._catch_response(hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 523, in _catch_response
      response = await self._recv_event(hconnection)
    File "/home/ubuntu/venv/lib/python3.7/site-packages/asks/request_object.py", line 588, in _recv_event
      event = hconnection.next_event()
    File "/home/ubuntu/venv/lib/python3.7/site-packages/h11/_connection.py", line 423, in next_event
      raise RemoteProtocolError("Can't receive data when peer state is ERROR")
  h11._util.RemoteProtocolError: Can't receive data when peer state is ERROR
```

**Comment by RmStorm** [comment]
Hello! I ran into this issue as well and I've been doing a little digging. I think the library actually handles retrying correctly judging by line 246-251:
https://github.com/theelous3/asks/blob/584a467e7a7bd52b56ee24c7ff3782e8423c2ba1/asks/sessions.py#L234-L251
I actually think the big problem is with line 236. It only closes a socket if the http response includes the `connection: close` header.

Now this is fine I think when the server closes the connection since it will include that header. However when the client requests the connection to be closed the server does not necessarily include that header as well on the response. It says so in the W3 standard that 'echoing' the  `connection: close` header  is not a 'MUST'.. it's a 'SHOULD', so there are servers out there that ignore it.

For reference I'm talking about [this document](https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html) and then specifically the first line of `8.1.2.1 Negotiation`, quoted here:

> An HTTP/1.1 server MAY assume that a HTTP/1.1 client intends to maintain a persistent connection unless a Connection header including the connection-token "close" was sent in the request. If the server chooses to close the connection immediately after sending the response, it SHOULD send a Connection header including the connection-token close. 

So like I said, since it says SHOULD there are servers out there that don't do this (cough cough unicorn/starlette) I will make an issue in their repo's as well to comply with the SHOULD but this can be resolved here as well. We just need to check the  `connection: close` header on both the response and the request!

Now to make this extra nice, the [default asks header includes `connection: close`](https://github.com/theelous3/asks/blob/584a467e7a7bd52b56ee24c7ff3782e8423c2ba1/asks/request_object.py#L169-L179) ensuring that this edge case is hit on every server that doesn't send that header back. Of course this is only a problem when using a session, otherwise the connection is not retained anyways and it's no problem.

**Comment by RmStorm** [comment]
So I wrote a fix that works pretty well, however it's very hard to test! Overly is used for server mocking in the tests and it uses h11 and h11 is implemented correctly and will pretty much not allow you to omit `connection: close` header. Sooo, I'm not sure how to go about this. I think I will just make the PR without a test and hope someone here has time to look at it.

**Comment by RmStorm** [comment]
@theelous3 @rnovatorov Does one of you have time to check my proposed solution in #168? Also I really think that `connection: close` should not be in the default headers when using a session. Isn't like the whole point of using a session to reuse the http connection over multiple request-response cycles?

Is there a reason the implementation is like this?:
https://github.com/theelous3/asks/blob/584a467e7a7bd52b56ee24c7ff3782e8423c2ba1/asks/request_object.py#L169-L179
