### ISSUE TITLE
DigestAuth broken

### ISSUE THREAD

**Issue by jgerry2002** [theelous3/asks#125]
Tried a very basic example. Unfortunately the IOT devices I am working with still use DigestAuth.

`import asks
import curio
from asks import BasicAuth, DigestAuth
asks.init('curio')

userinfo = ('user','admin')

async def simpledigesttest():
    getresponse = await asks.post('http://dumbiotdevice',auth=DigestAuth(userinfo))
    print(getresponse.content)

curio.run(simpledigesttest())`

Returns:
Task Crash: Task(id=56, name='simpledigesttest', state='TERMINATED')
Traceback (most recent call last):
  File "/opt/testenv/lib64/python3.6/site-packages/curio/kernel.py", line 736, in _run_coro
    trap = current._send(current.next_value)
  File "/opt/testenv/lib64/python3.6/site-packages/curio/task.py", line 167, in _task_runner
    return await coro
  File "<stdin>", line 2, in simpledigesttest
  File "/opt/testenv/lib64/python3.6/site-packages/asks/base_funcs.py", line 30, in request
    r = await s.request(method, url=uri, **kwargs)
  File "/opt/testenv/lib64/python3.6/site-packages/asks/sessions.py", line 214, in request
    await self._handle_exception(e, sock)
  File "/opt/testenv/lib64/python3.6/site-packages/asks/sessions.py", line 256, in _handle_exception
    raise e
  File "/opt/testenv/lib64/python3.6/site-packages/asks/sessions.py", line 184, in request
    sock, r = await req_obj.make_request()
  File "/opt/testenv/lib64/python3.6/site-packages/asks/request_object.py", line 216, in make_request
    response_obj = await self._request_io(req, req_body, h11_connection)
  File "/opt/testenv/lib64/python3.6/site-packages/asks/request_object.py", line 267, in _request_io
    response_obj)
  File "/opt/testenv/lib64/python3.6/site-packages/asks/request_object.py", line 672, in _auth_handler_post_check_retry
    _, r = await self.make_request()
  File "/opt/testenv/lib64/python3.6/site-packages/asks/request_object.py", line 192, in make_request
    asks_headers.update(await self._auth_handler_post_get_auth())
  File "/opt/testenv/lib64/python3.6/site-packages/asks/request_object.py", line 656, in _auth_handler_post_get_auth
    return await self.auth(authable_resp, self)
  File "/opt/testenv/lib64/python3.6/site-packages/asks/auth.py", line 167, in __call__
    'opaque="{}"'.format(str(auth_dict['opaque'],
KeyError: 'opaque'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/testenv/lib64/python3.6/site-packages/curio/kernel.py", line 818, in run
    return kernel.run(corofunc, *args)
  File "/opt/testenv/lib64/python3.6/site-packages/curio/kernel.py", line 179, in run
    raise ret_exc
  File "/opt/testenv/lib64/python3.6/site-packages/curio/kernel.py", line 736, in _run_coro
    trap = current._send(current.next_value)
  File "/opt/testenv/lib64/python3.6/site-packages/curio/task.py", line 167, in _task_runner
    return await coro
  File "<stdin>", line 2, in simpledigesttest
  File "/opt/testenv/lib64/python3.6/site-packages/asks/base_funcs.py", line 30, in request
    r = await s.request(method, url=uri, **kwargs)
  File "/opt/testenv/lib64/python3.6/site-packages/asks/sessions.py", line 214, in request
    await self._handle_exception(e, sock)
  File "/opt/testenv/lib64/python3.6/site-packages/asks/sessions.py", line 256, in _handle_exception
    raise e
  File "/opt/testenv/lib64/python3.6/site-packages/asks/sessions.py", line 184, in request
    sock, r = await req_obj.make_request()
  File "/opt/testenv/lib64/python3.6/site-packages/asks/request_object.py", line 216, in make_request
    response_obj = await self._request_io(req, req_body, h11_connection)
  File "/opt/testenv/lib64/python3.6/site-packages/asks/request_object.py", line 267, in _request_io
    response_obj)
  File "/opt/testenv/lib64/python3.6/site-packages/asks/request_object.py", line 672, in _auth_handler_post_check_retry
    _, r = await self.make_request()
  File "/opt/testenv/lib64/python3.6/site-packages/asks/request_object.py", line 192, in make_request
    asks_headers.update(await self._auth_handler_post_get_auth())
  File "/opt/testenv/lib64/python3.6/site-packages/asks/request_object.py", line 656, in _auth_handler_post_get_auth
    return await self.auth(authable_resp, self)
  File "/opt/testenv/lib64/python3.6/site-packages/asks/auth.py", line 167, in __call__
    'opaque="{}"'.format(str(auth_dict['opaque'],
KeyError: 'opaque'

**Comment by theelous3** [comment]
Just tested against httpbin's digest endpoint with qop to auth, working ok.

Added some prints internally:

```python3
>>> async def lol():
...     r = await get("http://httpbin.org/digest-auth/auth/lol/wat", auth=DigestAuth(("lol", "wat")))
...     print(r.history, r.status_code)
... 
>>> curio.run(lol)
Got www-authenticate header: Digest realm="me@kennethreitz.com", nonce="7ec4b487fd3feafdd25bb37f515b7c69", qop="auth", opaque="37e8ce69de747a7806e6b655554ecc20", algorithm=MD5, stale=FALSE
added a header: realm me@kennethreitz.com
added a header: nonce 7ec4b487fd3feafdd25bb37f515b7c69
added a header: qop auth
added a header: opaque 37e8ce69de747a7806e6b655554ecc20
added a header: algorithm MD5,
added a header: stale FALSE
[<Response 401 UNAUTHORIZED>] 200
>>> 
```
It's processing ok.

Can you print the www-authenticate header you're getting?

**Comment by jgerry2002** [comment]
Its likely the implementation of my crude iot devices simply missing something that is likely supposed to be there. 

I tested out a modification of auth.py by adding an if in there for "opaque". I excluded it based on the fact the dictionary returned by said crude iot device simply does not have the 'opaque' key in the dictionary and now the response is being returned properly.

`if 'opaque' in auth_dict:
           response_items = ['username="{}"'.format(str(usrname, self.encoding)),
                          'realm="{}"'.format(str(auth_dict['realm'],
                                                  self.encoding)),
                          'nonce="{}"'.format(str(auth_dict['nonce'],
                                                  self.encoding)),
                          'uri="{}"'.format(req_obj.path),
                          'response="{}"'.format(response),
                          'opaque="{}"'.format(str(auth_dict['opaque'],
                                                   self.encoding))]
        elif 'opaque' not in auth_dict:
           response_items = ['username="{}"'.format(str(usrname, self.encoding)),
                          'realm="{}"'.format(str(auth_dict['realm'],
                                                  self.encoding)),
                          'nonce="{}"'.format(str(auth_dict['nonce'],
                                                  self.encoding)),
                          'uri="{}"'.format(req_obj.path),
                          'response="{}"'.format(response),
                          ]
`

**Comment by jgerry2002** [comment]
The actual dictionary is this:
{'realm': b'Configuration', 'nonce': b'fc228c460e985dce460006501e5413dc', 'qop': b'auth'}

**Comment by theelous3** [comment]
lol classic IOT "auth" happenings here.

I guess just run your modified code with this device :)

**Comment by jgerry2002** [comment]
Yes it is, unfortunately I have thousands of the stupid things all with the same problem.

**Comment by jgerry2002** [comment]
You may want to think about including the few lines of code to fix this. Anything else with lighttpd may in fact have the same issue. Either way, the fast response was appreciated.
