### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by wku** [theelous3/asks#28]
import asks
import curio

asks.init('curio')

async def example(url):
    r = await asks.get(url)
    print(r.content)

#not work
url = 'https://simferopol.drom.ru/opel/meriva/24011092.html'

#work
#url = 'https://simferopol.drom.ru'
curio.run(example(url))

Traceback (most recent call last):
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request.py", line 524, in _catch_response
    response = await self._recv_event(hconnection)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request.py", line 583, in _recv_event
    event = hconnection.next_event()
  File "/home/wku/anaconda3/lib/python3.6/site-packages/h11/_connection.py", line 439, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/wku/anaconda3/lib/python3.6/site-packages/h11/_util.py", line 71, in _reraise_as_remote_protocol_error
    raise self
  File "/home/wku/anaconda3/lib/python3.6/site-packages/h11/_connection.py", line 420, in next_event
    event = self._extract_next_receive_event()
  File "/home/wku/anaconda3/lib/python3.6/site-packages/h11/_connection.py", line 361, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/h11/_readers.py", line 171, in maybe_read_from_SEND_RESPONSE_server
    matches = validate(status_line_re, lines[0])
  File "/home/wku/anaconda3/lib/python3.6/site-packages/h11/_util.py", line 91, in validate
    raise LocalProtocolError(msg)
h11._util.RemoteProtocolError: malformed data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/kernel.py", line 826, in _run_coro
    trap = current._send(current.next_value)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/task.py", line 96, in _task_runner
    return await coro
  File "/home/wku/Рабочий стол/[project]/[project_work]/[auto]/src/app/_/m.py", line 8, in example
    r = await asks.get(url)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/base_funcs.py", line 29, in request
    r = await s.request(method, url=uri, **kwargs)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/sessions.py", line 138, in request
    sock, r = await req_obj.make_request()
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request.py", line 203, in make_request
    response_obj = await self._request_io(req, req_body, hconnection)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request.py", line 240, in _request_io
    response_obj = await self._catch_response(hconnection)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request.py", line 527, in _catch_response
    response = await self._recv_event(hconnection)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request.py", line 583, in _recv_event
    event = hconnection.next_event()
  File "/home/wku/anaconda3/lib/python3.6/site-packages/h11/_connection.py", line 418, in next_event
    "Can't receive data when peer state is ERROR")
h11._util.RemoteProtocolError: Can't receive data when peer state is ERROR

**Comment by theelous3** [comment]
Hello again wku!

In order to fix this you'll have to update h11 to the latest development branch, where it adds tolerance for servers that give non-strictly conforming http status lines.

A good and standards conforming status line looks like this: `b'HTTP/1.1 200 OK\r\n'` however the server of the website you posted gives status lines without the reason phrase like this `b'HTTP/1.1 200\r\n'`.

Here is the section of code with comments in h11 that cover it:

https://github.com/njsmith/h11/blob/master/h11/_abnf.py#L96

(Note, that h11 is a dependency of asks.)

I'll look in to maybe forcing asks to use the development branch of h11 until it's updated on pypi. Thanks!

**Comment by wku** [comment]
Yes, thanks to this update solved the problem
