### ISSUE TITLE
KeyError: 'transfer-encoding'

### ISSUE THREAD

**Issue by SunDwarf** [theelous3/asks#32]
```
Traceback (most recent call last):
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/asks/request.py", line 549, in _catch_response
    if int(resp_data['headers']['content-length']) > 0:
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/asks/req_structs.py", line 79, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/curio/kernel.py", line 826, in _run_coro
    trap = current._send(current.next_value)
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/curio/task.py", line 96, in _task_runner
    return await coro
  File "/home/laura/dev/discord/automoderator/automoderator/core/engine.py", line 133, in _handle_rule
    await fn(ctx, **kwargs)
  File "/home/laura/dev/discord/automoderator/automoderator/core/engine.py", line 175, in action_delete_message
    await msg.delete()
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/curious/dataclasses/message.py", line 231, in delete
    await self._bot.http.delete_message(self.channel.id, self.id)
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/curious/http/httpclient.py", line 596, in delete_message
    data = await self.delete(url, "messages:{}".format(channel_id))
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/curious/http/httpclient.py", line 378, in delete
    return await self.request(("DELETE", bucket), method="DELETE", path=url, *args, **kwargs)
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/curious/http/httpclient.py", line 251, in request
    response = await self._make_request(*args, **kwargs)
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/curious/http/httpclient.py", line 212, in _make_request
    return await self.session.request(*args, headers=headers, **kwargs)
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/asks/sessions.py", line 156, in request
    sock, r = await req_obj.make_request()
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/asks/request.py", line 203, in make_request
    response_obj = await self._request_io(req, req_body, hconnection)
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/asks/request.py", line 240, in _request_io
    response_obj = await self._catch_response(hconnection)
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/asks/request.py", line 553, in _catch_response
    if resp_data['headers']['transfer-encoding'] == 'chunked':
  File "/home/laura/.local/share/virtualenvs/automoderator-nZfczLQS/lib/python3.6/site-packages/asks/req_structs.py", line 79, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'transfer-encoding'
```

Errors when a HTTP server sends neither a Content-Length nor a Transfer-Encoding.

**Comment by yifeikong** [comment]
Seems to be a bug. What is the url that causes the problem? maybe we should add it to test cases after fixing it.

**Comment by wku** [comment]
from urllib.parse   import quote

import asks
import curio
asks.init('curio')

async def example(url):
    r = await asks.get(url)
    print(r.content[:100])


#work
#url = "https://www.google.com.ua/search?q=" + quote("привет")
#curio.run(example(url))

#work
# url = 'https://www.ua-region.com.ua/search/?q='
# curio.run(example(url))

#work
# url = 'https://www.ua-region.com.ua/search/?q=r'
# curio.run(example(url))


#not work
# url = 'https://www.ua-region.com.ua/search/?q=rrr'
# curio.run(example(url))

#not work
url = 'https://www.ua-region.com.ua/search/?q=' + quote("привет")
curio.run(example(url))



"""
Traceback (most recent call last):
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request.py", line 549, in _catch_response
    if int(resp_data['headers']['content-length']) > 0:
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/req_structs.py", line 79, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/kernel.py", line 826, in _run_coro
    trap = current._send(current.next_value)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/task.py", line 96, in _task_runner
    return await coro
  File "/home/wku/Рабочий стол/[project]/[project_work]/[auto]/src/app/modules/tp.py", line 10, in example
    r = await asks.get(url)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/base_funcs.py", line 29, in request
    r = await s.request(method, url=uri, **kwargs)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/sessions.py", line 156, in request
    sock, r = await req_obj.make_request()
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request.py", line 203, in make_request
    response_obj = await self._request_io(req, req_body, hconnection)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request.py", line 240, in _request_io
    response_obj = await self._catch_response(hconnection)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request.py", line 552, in _catch_response
    if resp_data['headers']['transfer-encoding'] == 'chunked':
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/req_structs.py", line 79, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'transfer-encoding'

"""

**Comment by yifeikong** [comment]
Actually, what the server did is legitimate. According to [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.3.3), the client will have to read till the connection is closed is the server sends Connection: close and no content-length header
