### ISSUE TITLE
bug with timeout manager

### ISSUE THREAD

**Issue by yifeikong** [theelous3/asks#35]
```
ERROR:curio.debug:Task 5209 crashed
Traceback (most recent call last):
  File "/home/kongyifei/repos/crawlet/.venv/lib/python3.6/site-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kongyifei/repos/crawlet/.venv/src/asks/asks/request.py", line 524, in _catch_response
    response = await self._recv_event(hconnection)
  File "/home/kongyifei/repos/crawlet/.venv/src/asks/asks/request.py", line 583, in _recv_event
    event = hconnection.next_event()
  File "/home/kongyifei/repos/crawlet/.venv/lib/python3.6/site-packages/h11/_connection.py", line 439, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/kongyifei/repos/crawlet/.venv/lib/python3.6/site-packages/h11/_util.py", line 71, in _reraise_as_remote_protocol_error
    raise self
  File "/home/kongyifei/repos/crawlet/.venv/lib/python3.6/site-packages/h11/_connection.py", line 422, in next_event
    self._process_event(self.their_role, event)
  File "/home/kongyifei/repos/crawlet/.venv/lib/python3.6/site-packages/h11/_connection.py", line 238, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "/home/kongyifei/repos/crawlet/.venv/lib/python3.6/site-packages/h11/_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "/home/kongyifei/repos/crawlet/.venv/lib/python3.6/site-packages/h11/_state.py", line 253, in _fire_event_triggered_transitions
    .format(event_type, role, self.states[role]))
h11._util.RemoteProtocolError: can't handle event type <class 'h11._events.ConnectionClosed'> for SERVER in state SEND_RESPONSE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kongyifei/repos/crawlet/.venv/lib/python3.6/site-packages/curio/kernel.py", line 826, in _run_coro
    trap = current._send(current.next_value)
  File "/home/kongyifei/repos/crawlet/.venv/lib/python3.6/site-packages/curio/task.py", line 96, in _task_runner
    return await coro
  File "/home/kongyifei/repos/crawlet/.venv/src/asks/asks/request.py", line 203, in make_request
    response_obj = await self._request_io(req, req_body, hconnection)
  File "/home/kongyifei/repos/crawlet/.venv/src/asks/asks/request.py", line 240, in _request_io
    response_obj = await self._catch_response(hconnection)
  File "/home/kongyifei/repos/crawlet/.venv/src/asks/asks/request.py", line 527, in _catch_response
    response = await self._recv_event(hconnection)
  File "/home/kongyifei/repos/crawlet/.venv/src/asks/asks/request.py", line 583, in _recv_event
    event = hconnection.next_event()
  File "/home/kongyifei/repos/crawlet/.venv/lib/python3.6/site-packages/h11/_connection.py", line 418, in next_event
    "Can't receive data when peer state is ERROR")
h11._util.RemoteProtocolError: Can't receive data when peer state is ERROR
ERROR:Crawlet-spider:download error for https://bj.lianjia.com/ershoufang/101101673238.html, TaskGroupError(RemoteProtocolError)
Traceback (most recent call last):
  File "/home/kongyifei/repos/crawlet/crawlet/download.py", line 71, in process_request
    timeout=context.rule.get('timeout', 10),
  File "/home/kongyifei/repos/crawlet/.venv/src/asks/asks/sessions.py", line 158, in request
    sock, r = await self.timeout_manager(timeout, req_obj)
  File "/home/kongyifei/repos/crawlet/.venv/src/asks/asks/sessions.py", line 187, in timeout_manager
    req_obj.make_request)
  File "/home/kongyifei/repos/crawlet/.venv/lib/python3.6/site-packages/curio/task.py", line 446, in __aexit__
    await self.join(wait=self._wait)
  File "/home/kongyifei/repos/crawlet/.venv/lib/python3.6/site-packages/curio/task.py", line 435, in join
    raise TaskGroupError(exceptional)
curio.errors.TaskGroupError: TaskGroupError(RemoteProtocolError)
```

**Comment by yifeikong** [comment]
When this happens, disk io and cpu usage are all in a very high level

**Comment by yifeikong** [comment]
```
try:
    async with _async_lib.timeout_after(timeout):
        async with _async_lib.task_manager() as m:
            response_task = await m.spawn(
                req_obj.make_request)
        sock, r = response_task.result
except _async_lib.TaskTimeout:
    raise RequestTimeout
```

this code seems to be redundant to me, why do we need a `TaskGroup`, why not just `await req_obj.make_request()`

**Comment by theelous3** [comment]
Hi just back from holidays, going digging in to this and the other issues now :)
