### ISSUE TITLE
If there is a port number, it gives an error

### ISSUE THREAD

**Issue by wku** [theelous3/asks#48]
`
import asks
import curio
asks.init('curio')

async def example(url):
    r = await asks.get(url)
    print(r.content[:20])
    return r

curio.run (example('http://176.9.8.16:8081'))
`

**Comment by theelous3** [comment]
Can you paste a traceback?

**Comment by wku** [comment]
`
Task 2 crashed
Traceback (most recent call last):
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/kernel.py", line 826, in _run_coro
    trap = current._send(current.next_value)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/task.py", line 96, in _task_runner
    return await coro
  File "/home/wku/Рабочий стол/[project]/[project_work]/[+5-crawler+comment+me]/microservices/src/+/6-/MedReminderServer-master/medicine_service/l.py", line 6, in example
    r = await asks.get(url)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/base_funcs.py", line 29, in request
    r = await s.request(method, url=uri, **kwargs)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/sessions.py", line 157, in request
    sock, r = await req_obj.make_request()
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request_object.py", line 203, in make_request
    response_obj = await self._request_io(req, req_body, hconnection)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request_object.py", line 260, in _request_io
    response_obj = await self._redirect(response_obj)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request_object.py", line 333, in _redirect
    await self._get_new_sock()
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request_object.py", line 360, in _get_new_sock
    self.sock = await self.session._grab_connection(self.uri)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/sessions.py", line 300, in _grab_connection
    sock = await self._make_connection(host_loc)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/sessions.py", line 272, in _make_connection
    sock, port = await self._connect(host_loc)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/sessions.py", line 83, in _connect
    (netloc, int(port))), port
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/sessions.py", line 51, in _open_connection_http
    ssl=False)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/network.py", line 69, in open_connection
    sock = await socket.create_connection((host, port), source_addr)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/socket.py", line 43, in create_connection
    sock = await workers.run_in_thread(_socket.create_connection, *args, **kwargs)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/workers.py", line 94, in run_in_thread
    return await worker.apply(callable, args, call_on_cancel)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/workers.py", line 323, in apply
    return future.result()
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/workers.py", line 242, in result
    raise self._exception from None
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/workers.py", line 312, in run_callable
    future.set_result(func(*args))
  File "/home/wku/anaconda3/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/wku/anaconda3/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/kernel.py", line 826, in _run_coro
    trap = current._send(current.next_value)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/task.py", line 96, in _task_runner
    return await coro
  File "/home/wku/Рабочий стол/[project]/[project_work]/[+5-crawler+comment+me]/microservices/src/+/6-/MedReminderServer-master/medicine_service/l.py", line 6, in example
    r = await asks.get(url)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/base_funcs.py", line 29, in request
    r = await s.request(method, url=uri, **kwargs)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/sessions.py", line 157, in request
    sock, r = await req_obj.make_request()
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request_object.py", line 203, in make_request
    response_obj = await self._request_io(req, req_body, hconnection)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request_object.py", line 260, in _request_io
    response_obj = await self._redirect(response_obj)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request_object.py", line 333, in _redirect
    await self._get_new_sock()
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/request_object.py", line 360, in _get_new_sock
    self.sock = await self.session._grab_connection(self.uri)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/sessions.py", line 300, in _grab_connection
    sock = await self._make_connection(host_loc)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/sessions.py", line 272, in _make_connection
    sock, port = await self._connect(host_loc)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/sessions.py", line 83, in _connect
    (netloc, int(port))), port
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/sessions.py", line 51, in _open_connection_http
    ssl=False)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/network.py", line 69, in open_connection
    sock = await socket.create_connection((host, port), source_addr)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/socket.py", line 43, in create_connection
    sock = await workers.run_in_thread(_socket.create_connection, *args, **kwargs)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/workers.py", line 94, in run_in_thread
    return await worker.apply(callable, args, call_on_cancel)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/workers.py", line 323, in apply
    return future.result()
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/workers.py", line 242, in result
    raise self._exception from None
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/workers.py", line 312, in run_callable
    future.set_result(func(*args))
  File "/home/wku/anaconda3/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/wku/anaconda3/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wku/Рабочий стол/[project]/[project_work]/[+5-crawler+comment+me]/microservices/src/+/6-/MedReminderServer-master/medicine_service/l.py", line 10, in <module>
    curio.run (example('http://176.9.8.16:8081'))
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/kernel.py", line 877, in run
    return kernel.run(corofunc, *args, timeout=timeout)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/kernel.py", line 214, in run
    raise TaskError('Task Crashed') from ret_exc
curio.errors.TaskError: Task Crashed
`

**Comment by theelous3** [comment]
Playing around with this locally I find no issues. Requests like `'http://127.0.0.1:28001'` and so on are correctly split and connection attempts made etc.

Perhaps this is an issue with whatever it is you are calling? Can you provide more info?
