### ISSUE TITLE
asks 1.3.9 + Trio 0.3.0 + stream seems to be broken?

### ISSUE THREAD

**Issue by pmav99** [theelous3/asks#56]
```
$ pip freeze | grep -e trio -e curio -e asks
asks==1.3.9
curio==0.8
trio==0.3.0
```

Example: 

```python
import io
import asks
import trio
import curio

async def download_file(url, fd):
    """ Download file and save it to the provided fd. """
    r = await asks.get(url, stream=True)
    async with r.body:
        async for bytechunk in r.body:
            fd.write(bytechunk)
    fd.seek(0)

url = 'https://www.sec.gov/Archives/edgar/full-index/1993/QTR1/master.gz'

asks.init('curio')
fd = io.BytesIO()
curio.run(download_file, url, fd)
no_bytes = len(fd.read())
assert no_bytes == 446, no_bytes
print("curio OK")

asks.init('trio')
fd = io.BytesIO()
trio.run(download_file, url, fd)
no_bytes = len(file.read())
assert no_bytes == 446, no_bytes
print("trio OK")
```
The curio code downloads the file just fine, but trio throws an exception.

``` python
Traceback (most recent call last):
  File "tri.py", line 58, in <module>
    trio.run(download_file, url, fd)
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_core/_run.py", line 1225, in run
    return result.unwrap()
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_core/_result.py", line 119, in unwrap
    raise self.error
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_core/_run.py", line 1334, in run_impl
    msg = task.coro.send(next_send)
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_core/_run.py", line 923, in init
    self.entry_queue.spawn()
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_util.py", line 109, in __aexit__
    await self._agen.asend(None)
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/async_generator/_impl.py", line 274, in asend
    return await self._do_it(self._it.send, value)
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/async_generator/_impl.py", line 290, in _do_it
    return await ANextIter(self._it, start_fn, *args)
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/async_generator/_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_core/_run.py", line 318, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
    yield scope
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_core/_multierror.py", line 144, in __exit__
    raise filtered_exc
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
    yield scope
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_core/_run.py", line 318, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_core/_run.py", line 427, in _nested_child_finished
    raise MultiError(self._pending_excs)
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_core/_run.py", line 1334, in run_impl
    msg = task.coro.send(next_send)
  File "tri.py", line 43, in download_file
    fd.write(bytechunk)
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/asks/response_objects.py", line 186, in __aexit__
    await self.close()
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/asks/response_objects.py", line 183, in close
    await self.sock.close()
  File "/home/feanor/.virtualenvs/xbrl/lib/python3.6/site-packages/trio/_ssl.py", line 399, in __getattr__
    raise AttributeError(name)
AttributeError: close
```

**Comment by theelous3** [comment]
Fixed. Trio uses `.aclose` on its streams rather than `.close`, bad presumption on my part.

https://github.com/theelous3/asks/commit/c0b7fb4dec18452c0f8c0028d0e892c27d6a2ea2

**Comment by theelous3** [comment]
The build on travis has gone absolutely mental. Tests all ok locally. Random http stuff to the net ok from local. Think it's just travis / the build env going craycray.
