### ISSUE TITLE
Allow uploading BytesIO as files

### ISSUE THREAD

**Issue by SunDwarf** [theelous3/asks#58]
Right now this fails spectactularly:

```
Traceback (most recent call last):
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/asks/request_object.py", line 470, in _multipart
    pkg_body = await self._file_manager(v)
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/asks/request_object.py", line 495, in _file_manager
    async with asynclib.aopen(path, 'rb') as f:
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/curio/file.py", line 139, in __aenter__
    self._fileobj = await run_in_thread(partial(open, *self._open_args, **self._open_kwargs))
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/curio/workers.py", line 94, in run_in_thread
    return await worker.apply(callable, args, call_on_cancel)
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/curio/workers.py", line 323, in apply
    return future.result()
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/curio/workers.py", line 242, in result
    raise self._exception from None
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/curio/workers.py", line 312, in run_callable
    future.set_result(func(*args))
TypeError: expected str, bytes or os.PathLike object, not dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/curious/commands/context.py", line 265, in invoke
    return await matched_command(self, *converted_args, **converted_kwargs)
  File "/home/laura/dev/discord/jokusoramame/jokusoramame/plugins/analytics.py", line 284, in command_server_distribution
    await ctx.channel.messages.upload(buf, filename="plot.png")
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/curious/dataclasses/channel.py", line 351, in upload
    filename=filename, content=message_content)
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/curious/core/httpclient.py", line 617, in send_file
    body=payload, files=files)
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/curious/core/httpclient.py", line 393, in post
    return await self.request(("POST", bucket), method="POST", path=url, *args, **kwargs)
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/curious/core/httpclient.py", line 267, in request
    response = await self._make_request(*args, **kwargs)
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/curious/core/httpclient.py", line 224, in _make_request
    return await asks.request(*args, headers=headers, timeout=5, **kwargs)
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/asks/base_funcs.py", line 29, in request
    r = await s.request(method, url=uri, **kwargs)
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/asks/sessions.py", line 163, in request
    sock, r = await self.timeout_manager(timeout, req_obj)
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/asks/sessions.py", line 188, in timeout_manager
    sock, r = await req_obj.make_request()
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/asks/request_object.py", line 169, in make_request
    content_type, content_len, body = await self._formulate_body()
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/asks/request_object.py", line 398, in _formulate_body
    body = await self._multipart(self.files)
  File "/home/laura/.local/share/virtualenvs/jokusoramame-SR0dS4Ee/lib/python3.6/site-packages/asks/request_object.py", line 484, in _multipart
    pkg_body = bytes(v, self.encoding) + b'\r\n'
TypeError: encoding without a string argument
```

**Comment by theelous3** [comment]
Is there any more info on this?
