### ISSUE TITLE
Please fix `pydoc3 asks.sessions`

### ISSUE THREAD

**Issue by smurfix** [theelous3/asks#75]
```
$ pydoc3 asks.sessions
Traceback (most recent call last):
  File "/usr/bin/pydoc3", line 5, in <module>
    pydoc.cli()
  File "/usr/lib/python3.5/pydoc.py", line 2623, in cli
    help.help(arg)
  File "/usr/lib/python3.5/pydoc.py", line 1903, in help
    elif request: doc(request, 'Help on %s:', output=self._output)
  File "/usr/lib/python3.5/pydoc.py", line 1640, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/lib/python3.5/pydoc.py", line 1633, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/usr/lib/python3.5/pydoc.py", line 374, in document
    if inspect.ismodule(object): return self.docmodule(*args)
  File "/usr/lib/python3.5/pydoc.py", line 1113, in docmodule
    for key, value in inspect.getmembers(object, inspect.isclass):
  File "/usr/lib/python3.5/inspect.py", line 316, in getmembers
    if not predicate or predicate(value):
  File "/usr/lib/python3.5/inspect.py", line 78, in isclass
    return isinstance(object, type)
  File "/usr/lib/python3/dist-packages/multio/__init__.py", line 397, in __getattribute__
    raise RuntimeError("multio.init() wasn't called")
RuntimeError: multio.init() wasn't called
```

**Comment by theelous3** [comment]
:D Yep.

Need to give the examples a run through. Feel free to help!

**Comment by smurfix** [comment]
resolved by switching to anyio.
