### ISSUE TITLE
Weird behavior with Session.get and streaming?

### ISSUE THREAD

**Issue by sztomi** [theelous3/asks#85]
I might be doing something wrong, but I can't figure this out.

I have the following code that talks to a pypi simple API (think `self.session.base_location` being set to `https://pypi.org/simple/`):

```python
  async def get(self, path, stream=False):
    self.log.debug(f"GET {path}")
    self.log.debug(f"stream = {stream}")
    return await self.session.get(path=path, auth=self.auth, stream=stream)
```

Now, I'm doing this:

```python
await api.get("/requests")   # (1)
```

I just added the `stream` parameter with the default value of `False`. And suddenly my code expecting a `Response` breaks because the return value is now `StreamResponse` (despite `stream` being `False`). My log output:

```
2018-09-22 13:41:51,433   bib.installer.installer  DEBUG    - Base URL: https://pypi.org/simple
2018-09-22 13:41:51,433   bib.installer.installer  DEBUG    - Getting metadata of requests
2018-09-22 13:41:51,433   bib.api.legacy           DEBUG    - GET /requests
2018-09-22 13:41:51,433   bib.api.legacy           DEBUG    - stream = False
Traceback (most recent call last):
  File "/home/tamas/.local/share/virtualenvs/bib-wgx9oSkl/bin/bib", line 11, in <module>
    load_entry_point('bib', 'console_scripts', 'bib')()
  File "/home/tamas/.local/share/virtualenvs/bib-wgx9oSkl/lib/python3.7/site-packages/trio_click/core.py", line 748, in __call__
    return trio.run(main,*args)
  File "/home/tamas/.local/share/virtualenvs/bib-wgx9oSkl/lib/python3.7/site-packages/trio/_core/_run.py", line 1328, in run
    raise runner.main_task_outcome.error
  File "/home/tamas/.local/share/virtualenvs/bib-wgx9oSkl/lib/python3.7/site-packages/trio_click/core.py", line 720, in main
    rv = await self.invoke(ctx)
  File "/home/tamas/.local/share/virtualenvs/bib-wgx9oSkl/lib/python3.7/site-packages/trio_click/core.py", line 1117, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/home/tamas/.local/share/virtualenvs/bib-wgx9oSkl/lib/python3.7/site-packages/trio_click/core.py", line 936, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/home/tamas/.local/share/virtualenvs/bib-wgx9oSkl/lib/python3.7/site-packages/trio_click/core.py", line 560, in invoke
    rv = await rv
  File "/home/tamas/projects/bib/bib/cli.py", line 19, in install
    await installer.fetch_pkg(pkg)
  File "/home/tamas/projects/bib/bib/installer/installer.py", line 65, in fetch_pkg
    url = await self._fetch_metadata(pkg)
  File "/home/tamas/projects/bib/bib/installer/installer.py", line 37, in _fetch_metadata
    releases = await self.api.get_releases(pkg)
  File "/home/tamas/projects/bib/bib/api/legacy.py", line 22, in get_releases
    data = await trio.run_sync_in_worker_thread(parse_simple_index, resp.text)
AttributeError: 'StreamResponse' object has no attribute 'text'
```

However, if I do this:

```python
  async def get(self, path, stream=False):
    self.log.debug(f"GET {path}")
    self.log.debug(f"stream = {stream}")
    if stream:
      return await self.session.get(path=path, auth=self.auth, stream=stream)
    return await self.session.get(path=path, auth=self.auth)
```

i.e. not pass `stream` if it's false, the line marked with (1) works as expected and this error goes away. 

Unlike the code which previously used `asks.get` for a streaming response. I changed it to use the above function (to reuse the session). Now, even though I pass `stream=True` in this case, I still get `Response`/`bytes` instead of `StreamResponse`:

```python
whl_resp = await self.api.get(url, stream=True)  # (2)
fname = url.split("/")[-1]
output_name = trio.Path(self.target_dir / fname)
self.log.debug(type(whl_resp))
self.log.debug(type(whl_resp.body))
```

My log output for this second code block:

```
2018-09-22 13:34:53,307   bib.api.legacy           DEBUG    - GET /requests-2.19.1-py2.py3-none-any.whl
2018-09-22 13:34:53,307   bib.api.legacy           DEBUG    - stream = True
2018-09-22 13:34:53,592   bib.installer.installer  DEBUG    - <class 'asks.response_objects.Response'>
2018-09-22 13:34:53,592   bib.installer.installer  DEBUG    - <class 'bytes'>
```

As a result, my code that follows this [example](https://asks.readthedocs.io/en/latest/idioms.html#handling-response-body-content-downloads-etc) for streamed downloads breaks (because the body is `bytes`).

I would expect the following behavior:

  * If I pass `stream=True` to `Session.get`, the response becomes a `StreamResponse` (regardless of actual streaming taking place)
  * If I pass `stream=False` or don't pass `stream` at all, the response is `Response` and body is `bytes` 

Am I doing something wrong or is this a bug?

**Comment by theelous3** [comment]
This sounds buggy. Time for coffee.

**Comment by sztomi** [comment]
For one, (without knowing the codebase), this seems fishy to me: https://github.com/theelous3/asks/blob/master/asks/request_object.py#L574

I *think* this should test for truthyness and not for not being `None`. That explains why passing in `False` makes it stream. The other part I'm not sure about.

**Comment by theelous3** [comment]
So I've found another oddity while looking at this. For whatever bird-brained reason, we were only allowing `StreamResponse`s for cases where there could be a body. In some far off sense this makes some sense, but makes for an extreme stupid api.

I've removed this, and the `None` check on `stream` arg.

https://github.com/theelous3/asks/commit/0d314dbf5446f17778cd94e9be7463378d436e85

**Comment by sztomi** [comment]
Thanks! And sorry for disturbing the extreme comfort of your bed :D

I tried and it seems this fixed the problem. I don't know if this is related to the change though: 

```
2018-09-23 16:30:10,070   bib.installer.installer  DEBUG    - Base URL: https://<my index>/api/pypi/pypi-tools-and-cache/simple                                                                 
2018-09-23 16:30:10,070   bib.installer.installer  DEBUG    - Getting metadata of requests                                                                                                                           
2018-09-23 16:30:10,070   bib.api.legacy           DEBUG    - GET /requests                                                                                                                                          
2018-09-23 16:30:10,070   bib.api.legacy           DEBUG    - stream = False                                                                                                                                         
/home/tamas/.local/share/virtualenvs/bib-wgx9oSkl/src/asks/asks/request_object.py:270: RuntimeWarning: coroutine 'Request._location_auth_protect' was never awaited                                                  
  response_obj = await self._redirect(response_obj) 
```

I'm using basic HTTP auth to access the index. The authentication is successful but I get that warning.

**Comment by theelous3** [comment]
@sztomi first of all, thanks for the detailed isssue and effort. Love it. Secondly, I'll take a look at that auth thing, but in a diff issue. Closing this for now :)
