### ISSUE TITLE
exceptions are a mess (trio)

### ISSUE THREAD

**Issue by belm0** [theelous3/asks#89]
```python
import asks
import trio
asks.init('trio')

async def main():
    await asks.get('example.com')

trio.run(main)
```
I was expecting something from asks.errors but got the following.  It's really an implementation detail that there are multiple tasks in flight (yielding a MultiError).  Not straightforward for trio newbies.
```
trio.MultiError: ConnectionRefusedError(61, 'Error in connect: Connection refused'), ConnectionRefusedError(61, 'Error in connect: Connection refused')

Details of embedded exception 1:

  Traceback (most recent call last):
    File "/.../python3.6/site-packages/trio/_highlevel_open_tcp_stream.py", line 281, in attempt_connect
      await sock.connect(target_sockaddr)
    File "/.../python3.6/site-packages/trio/_socket.py", line 704, in connect
      raise OSError(err, "Error in connect: " + _os.strerror(err))
  ConnectionRefusedError: [Errno 61] Error in connect: Connection refused

Details of embedded exception 2:

  Traceback (most recent call last):
    File "/.../python3.6/site-packages/trio/_highlevel_open_tcp_stream.py", line 281, in attempt_connect
      await sock.connect(target_sockaddr)
    File "/.../python3.6/site-packages/trio/_socket.py", line 704, in connect
      raise OSError(err, "Error in connect: " + _os.strerror(err))
  ConnectionRefusedError: [Errno 61] Error in connect: Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "asks_exception.py", line 11, in <module>
    trio.run(main)
  File "/.../python3.6/site-packages/trio/_core/_run.py", line 1328, in run
    raise runner.main_task_outcome.error
  File "asks_exception.py", line 8, in main
    await asks.get('example.com')
  File "/.../python3.6/site-packages/asks/base_funcs.py", line 30, in request
    r = await s.request(method, url=uri, **kwargs)
  File "/.../python3.6/site-packages/asks/sessions.py", line 170, in request
    connection_timeout, self._grab_connection, url)
  File "/.../python3.6/site-packages/asks/utils.py", line 15, in timeout_manager
    return (await coro(*args))
  File "/.../python3.6/site-packages/asks/sessions.py", line 361, in _grab_connection
    sock = await self._make_connection(host_loc)
  File "/.../python3.6/site-packages/asks/sessions.py", line 335, in _make_connection
    sock, port = await self._connect(host_loc)
  File "/.../python3.6/site-packages/asks/sessions.py", line 103, in _connect
    (host, int(port))), port
  File "/.../python3.6/site-packages/asks/sessions.py", line 81, in _open_connection_https
    source_addr=self.source_address)
  File "/.../python3.6/site-packages/multio/_event_loop_wrappers.py", line 29, in trio_open_connection
    sock = await trio.open_ssl_over_tcp_stream(host, port)
  File "/.../python3.6/site-packages/trio/_highlevel_ssl_helpers.py", line 62, in open_ssl_over_tcp_stream
    happy_eyeballs_delay=happy_eyeballs_delay,
  File "/.../python3.6/site-packages/trio/_highlevel_open_tcp_stream.py", line 312, in open_tcp_stream
    raise OSError(msg) from trio.MultiError(oserrors)
OSError: all attempts to connect to :80 failed
```

**Comment by theelous3** [comment]
My general ethos is that if the issue happens outside of the implementation of a lib you shouldn't be doing anything to it. In this case, the socket stuff isn't happening in asks so if we catch it we may be silencing useful information,

Also, I can't remember or have never tried explicitly catching a silencing something that would be part of a multierror, so the behaviour there may be strange. It's something to look in to anyway, and a worthwhile discussion to have.

**Comment by belm0** [comment]
Wondering if asks should catch the MultiError ConnectionRefusedError and re-raise as ConnectionRefusedError.

@njsmith what's a library to do in this case?

**Comment by theelous3** [comment]
Pros and cons of aliasing the actual exception with the same name:

Pros:

- You can write catch alls like `except AsksException`

Cons:
- You have two things with the same name so your namespace gets messier.
    - If you do not name them the same, you lose the clear connection between the two and you are no longer aliasing, but renaming, and that is v bad.
- Your traceback gets even longer.
- Messy code that is inspecting the contents of `MultiError`s and making decisions about what to alias and what to allow through. Probably breaks trio.

**Comment by belm0** [comment]
I'm not suggesting aliasing ConnectionRefusedError.  Simply re-raise the MultiError of (ConnectionRefusedError, ConnectionRefusedError), which is an implementation detail, as ConnectionRefusedError.

Trio MultiError already has utilities for filtering and catching MultiErrors.  I think the onus is on asks rather than the asks user, again because it's an implementation detail of the task hierarchy used within asks.

**Comment by njsmith** [comment]
@belm0 This exception is coming straight out of `trio.open_tcp_stream`, so not really asks's fault :-).

Also, it's not a MultiError. If you look at the bottom of the traceback, the actual exception being raised is:

```
OSError: all attempts to connect to :80 failed
```

...I don't know why the host name is missing, that looks like a bug of some sort.

Anyway, the `MultiError` and `ConnectionRefusedError`s you see in the traceback are that `OSError`'s `__cause__` (notice the "The above exception was the direct cause of the following exception" text). Basically `open_tcp_stream` attempted to connect multiple ways, and then consolidated all of those into an `OSError`, with some details about the individual failures stuck into the `__cause__` in case they help in debugging. (And with [MultiError v2](https://github.com/python-trio/trio/issues/611), we'll also have some extra metadata there to describe what the two connection attempts that failed were.)

So... there's a question whether asks should catch the `OSError` and replace it with something like an `asks.ConnectionFailedError`. I can't answer that; it's something the asks devs have to decide.

There's also a question whether `open_tcp_stream` is doing the nicest thing it could here... but for that we should move over to the trio tracker :-)

**Comment by belm0** [comment]
@njsmith thank you for clarifying that.  I'll follow up on trio about improving the exception message.

@theelous3 re-raising something like `asks.ConnectionFailedError` doesn't sound bad to me, especially if there could be a few different underlying exceptions causing a failure, or if the exception may vary by async library.

**Comment by belm0** [comment]
Actually there is more to this.  `open_tcp_stream()` only takes a host and a port.  So an issue is that asks is not identifying the lack of a stream earlier.  It's probably passing empty string as host.

asks should probably raise it's own error for malformed URL

**Comment by belm0** [comment]
njsmith wrote:
> So... there's a question whether asks should catch the OSError and replace it with something like an asks.ConnectionFailedError. I can't answer that; it's something the asks devs have to decide.

We've had bad experience with this recently due to `anyio` changing the exception it raises on connection error (from `ConnectionError` to `OSError`).  It broke all of our client code using `asks`.

`asks` should transform the exceptions from `anyio`, which are an implementation detail, to `asks.ConnectionFailedError`.  @theelous3 🙏

**Comment by theelous3** [comment]
@belm0 that's a fair point. Let's doit :)
